---

# nvm dependencies
nvn_deps:
  - git
  - curl
  - build-essential
  - libssl-dev

# nvm git repository
nvm_git_repo: "https://github.com/creationix/nvm.git"

# nvm version
nvm_version: v0.31.0

# nvm install dir
nvm_install_dir: /usr/local/nvm

# nvm activation shell
nvm_nvmsh: '{{ nvm_install_dir }}/nvm.sh'

# nvm profile item
nvm_profile: '/etc/profile.d/nvm.sh'

nvm_temp_download_path: '/tmp'

nvm_latest_installer: 'https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh'

# which versions of node do you desire, _without_ the leading 'v'
nvm_nodes:
  - '4'

# default node version
nvm_node_default: '4'

# any package you would like to install globally?
nvm_npm_pkg:
  - npm@3

# Arbitrary phrase playbook  will be looking for in 'nvm ls' result stdout (not used but useful)
nvm_node_default_version_pattern: "node -> stable (-> v{{ nvm_node_version }}) (default)"
