---

- name: Debian | install packages
  apt: pkg={{ item }} state=installed
  with_items: "{{ php_nginx_packages }}"
  register: php_nginx_install

- name: ensure PHP-FPM is started and enabled
  service: name=php5-fpm state=started enabled=yes
  tags: php-fpm
